#!/usr/bin/env node

/* jslint node: true */
'use strict';

var nats = require('nats');
var argv = require('minimist')(process.argv.slice(2));

var url = argv.s || nats.DEFAULT_URI;
var creds = argv.creds;
var max = argv.n || 1;
var subject = argv._[0];
var msg = argv._[1] || '';

if (!subject) {
    console.log('Usage: node-req  [-s server] [--creds file] [-n max_responses] <subject> [msg]');
    process.exit();
}

// Connect to NATS server.
var nc = nats.connect(url, nats.creds(creds));

nc.request(subject, msg, {
    max: max
}, function(response) {
    console.log('Received: ' + response);
});

nc.on('unsubscribe', function(e) {
    process.exit();
});

nc.on('error', function(e) {
    console.log('Error [' + nc.currentServer + ']: ' + e);
    process.exit();
});
